"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[mgr]
cwd = { fg = "#d8e6e6", bg = "#171928" }
hovered = { fg = "#171928", bg = "#8b75d9", bold = true }
preview_hovered = { fg = "#171928", bg = "#0396b3", italic = true }
find_keyword = { fg = "#0396b3", bold = true }
find_position = { fg = "#ccd663" }
symlink_target = { fg = "#8b75d9" }
marker_copied = { fg = "#171928", bg = "#2dcc82" }
marker_cut = { fg = "#171928", bg = "#cc5860" }
marker_marked = { fg = "#171928", bg = "#d154a1" }
marker_selected = { fg = "#171928", bg = "#8b75d9" }
count_copied = { fg = "#2dcc82" }
count_cut = { fg = "#cc5860" }
count_selected = { fg = "#8b75d9" }
border_symbol = "│"
border_style = { fg = "#2a2e45" }

[mode]
normal_main = { fg = "#d8e6e6", bg = "#171928" }
normal_alt  = { fg = "#d8e6e6", bg = "#2a2e45" }
select_main = { fg = "#171928", bg = "#8b75d9", bold = true }
select_alt  = { fg = "#171928", bg = "#0396b3", bold = true }
unset_main  = { fg = "#8e94b8", bg = "#171928", dim = true }
unset_alt   = { fg = "#8e94b8", bg = "#2a2e45", dim = true }

[status]
overall = { fg = "#171928", bg = "#8b75d9" }
perm_sep = { fg = "#2a2e45" }
perm_type = { fg = "#0396b3" }
perm_read = { fg = "#2dcc82" }
perm_write = { fg = "#ccd663" }
perm_exec = { fg = "#cc5860" }
progress_label = { fg = "#d8e6e6" }
progress_normal = { fg = "#8b75d9" }
progress_error = { fg = "#cc2935" }

[tabs]
active = { fg = "#171928", bg = "#8b75d9", bold = true }
inactive = { fg = "#d8e6e6", bg = "#171928" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[which]
cols = 1
mask = { fg = "#171928", bg = "#2a2e45" }
cand = { fg = "#8b75d9", bold = true }
rest = { fg = "#d8e6e6" }
desc = { fg = "#d154a1" }
separator = "→"
separator_style = { fg = "#0396b3" }

[confirm]
border = { fg = "#2a2e45" }
title = { fg = "#8b75d9", bold = true }
content = { fg = "#d8e6e6" }
list = { fg = "#d8e6e6" }
btn_yes = { fg = "#171928", bg = "#2dcc82", bold = true }
btn_no  = { fg = "#171928", bg = "#cc5860", bold = true }
btn_labels = ["Yes", "No"]

[input]
border = { fg = "#2a2e45" }
title = { fg = "#8b75d9" }
value = { fg = "#d8e6e6" }
selected = { fg = "#171928", bg = "#d154a1" }

[pick]
border = { fg = "#2a2e45" }
active = { fg = "#171928", bg = "#8b75d9", bold = true }
inactive = { fg = "#d8e6e6", bg = "#171928" }

[cmp]
border = { fg = "#2a2e45" }
active = { fg = "#171928", bg = "#0396b3" }
inactive = { fg = "#d8e6e6", bg = "#171928" }
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "#2a2e45" }
title = { fg = "#8b75d9", bold = true }
hovered = { fg = "#171928", bg = "#0396b3" }

[help]
on = { fg = "#2dcc82" }
run = { fg = "#0396b3" }
desc = { fg = "#d8e6e6" }
hovered = { fg = "#171928", bg = "#8b75d9" }
footer = { fg = "#2a2e45" }

[notify]
title_info = { fg = "#0396b3", bold = true }
title_warn = { fg = "#ccd663", bold = true }
title_error = { fg = "#cc5860", bold = true }
icon_info = ""
icon_warn = ""
icon_error = ""