#!/usr/bin/env bash
set -euo pipefail

THEME_DIR="${HOME}/.config/colors"
THEME_JSON="${THEME_DIR}/colors.json"
ACTIVE_THEME_FILE="${THEME_DIR}/active_theme.json"

KITTY_THEME_FILE="${HOME}/.config/kitty/theme.conf"
YAZI_THEME_FILE="${HOME}/.config/yazi/theme.toml"

die() { echo "Error: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "Missing dependency: $1"; }

list_themes() {
  jq -r '.themes | keys[]' "$THEME_JSON"
}

theme_exists() {
  jq -e --arg t "$1" '.themes[$t] != null' "$THEME_JSON" >/dev/null
}

write_active_theme() {
  mkdir -p "$THEME_DIR"
  printf '{ "active": "%s" }\n' "$1" > "$ACTIVE_THEME_FILE"
}

apply_yazi_theme() {
  local t="$1"
  local yazi_theme
  yazi_theme="$(jq -r --arg t "$t" '.themes[$t].yazi.theme // empty' "$THEME_JSON")"
  [[ -z "$yazi_theme" ]] && return 0
  [[ -f "$YAZI_THEME_FILE" ]] || return 0

  if grep -qE '^[[:space:]]*theme[[:space:]]*=' "$YAZI_THEME_FILE"; then
    sed -i.bak -E "s|^[[:space:]]*theme[[:space:]]*=.*$|theme = \"${yazi_theme}\"|" "$YAZI_THEME_FILE"
  else
    printf '\ntheme = "%s"\n' "$yazi_theme" >> "$YAZI_THEME_FILE"
  fi
  rm -f "${YAZI_THEME_FILE}.bak"
}

apply_kitty_theme() {
  local t="$1"
  local outdir; outdir="$(dirname "$KITTY_THEME_FILE")"
  mkdir -p "$outdir"

  # Build kitty color conf from the theme's "ghostty" palette in colors.json [file:5]
  jq -r --arg t "$t" '
    .themes[$t].ghostty as $g
    | if $g == null then
        empty
      else
        "# Auto-generated by colorselector.sh. Do not edit.",
        "background " + $g.background,
        "foreground " + $g.foreground,
        "cursor " + $g.cursor,
        "color0 " + $g.color0,
        "color1 " + $g.color1,
        "color2 " + $g.color2,
        "color3 " + $g.color3,
        "color4 " + $g.color4,
        "color5 " + $g.color5,
        "color6 " + $g.color6,
        "color7 " + $g.color7,
        "color8 " + $g.color8,
        "color9 " + $g.color9,
        "color10 " + $g.color10,
        "color11 " + $g.color11,
        "color12 " + $g.color12,
        "color13 " + $g.color13,
        "color14 " + $g.color14,
        "color15 " + $g.color15
      end
  ' "$THEME_JSON" > "$KITTY_THEME_FILE"

  # Live-apply to running kitty (if any). --configured makes new windows in that instance use it. [web:40]
  if command -v kitty >/dev/null 2>&1; then
    kitty @ set-colors --all --configured "$KITTY_THEME_FILE" >/dev/null 2>&1 || true
  fi
}

nudge_neovim_reload() {
  # Keep your existing pattern: update active_theme.json then ask nvim to reload if a socket is present. [file:8]
  if [[ -n "${NVIM-}" && -S "${NVIM}" ]]; then
    nvim --server "$NVIM" --remote-send ':lua require("core.theme").setup()<CR>' >/dev/null 2>&1 || true
  elif [[ -S "/tmp/nvim.sock" ]]; then
    nvim --server "/tmp/nvim.sock" --remote-send ':lua require("core.theme").setup()<CR>' >/dev/null 2>&1 || true
  fi
}

usage() {
  cat <<'EOF'
Usage:
  colorselector.sh --list
  colorselector.sh THEME_KEY

Notes:
- Reads ~/.config/colors/colors.json
- Writes ~/.config/colors/active_theme.json
- Writes ~/.config/kitty/theme.conf and live-applies via `kitty @ set-colors`
EOF
}

main() {
  need jq

  [[ -f "$THEME_JSON" ]] || die "Missing: $THEME_JSON"

  if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
    usage; exit 0
  fi

  if [[ "$1" == "--list" || "$1" == "-l" ]]; then
    list_themes; exit 0
  fi

  local theme="$1"
  theme_exists "$theme" || die "Theme not found: $theme"

  write_active_theme "$theme"
  apply_kitty_theme "$theme"
  apply_yazi_theme "$theme"
  nudge_neovim_reload

  echo "Activated: $theme in Kitty, NeoVim and yazi"
}

main "$@"
