#!/usr/bin/env bash
set -euo pipefail

# --- Configuration ---
THEME_DIR="$HOME/.config/colors"
THEME_JSON="$THEME_DIR/colors.json"
GHOSTTY_TEMPLATES="$HOME/.config/colors/templates"
GHOSTTY_TEMPLATE="$GHOSTTY_TEMPLATES/ghostty.template"
GHOSTTY_DIR="$HOME/.config/ghostty"
GHOSTTY_THEMES_DIR="$GHOSTTY_DIR/themes"
GHOSTTY_CONFIG="$GHOSTTY_DIR/config"
ACTIVE_THEME_FILE="$THEME_DIR/active_theme.json"
YAZI_CONFIG_FILE="$HOME/.config/yazi/theme.toml"
NUSHELL_THEME_FILE="$HOME/.config/nushell/theme.nu"

# --- Utilities ---
error() { echo -e "\n❌ Error: $1" >&2; exit 1; }

# --- Theme Validation ---
theme_exists() {
  jq -e ".themes.\"$1\"" "$THEME_JSON" >/dev/null || error "Theme '$1' not found in $THEME_JSON."
}

list_themes() {
  echo "Available themes:"
  jq -r '.themes | keys | .[]' "$THEME_JSON" | sed 's/^/  - /'
}

# --- Application Modules ---
render_ghostty_theme() {
  local theme_name="$1"
  mkdir -p "$GHOSTTY_THEMES_DIR"
  [ -f "$GHOSTTY_TEMPLATE" ] || error "Ghostty template not found at $GHOSTTY_TEMPLATE"

  local theme_conf="$GHOSTTY_THEMES_DIR/${theme_name}.conf"
  local ghostty_current_symlink="$GHOSTTY_THEMES_DIR/current.conf"
  local new_config
  
  # Use jq to build the config from the template
  new_config=$(jq -r ".themes[\"$theme_name\"].ghostty | to_entries | reduce .[] as \$item (\"$(cat "$GHOSTTY_TEMPLATE")\"; gsub(\"%%\" + (\$item.key | ascii_upcase) + \"%%\"; \$item.value))" "$THEME_JSON")

  printf '%s\n' "$new_config" > "$theme_conf"
  ln -sfn "$theme_conf" "$ghostty_current_symlink"

  # Ensure the main config includes our theme
  if ! grep -q "include $ghostty_current_symlink" "$GHOSTTY_CONFIG" &>/dev/null; then
    printf '\n# Generated by colorselector.sh\ninclude %s\n' "$ghostty_current_symlink" >> "$GHOSTTY_CONFIG"
  fi
  
  printf "Ghostty… "
}

apply_yazi_theme() {
  local theme_name="$1"
  if ! jq -e ".themes[\"$theme_name\"].yazi.theme" "$THEME_JSON" >/dev/null; then return; fi
  local yazi_theme; yazi_theme=$(jq -r ".themes[\"$theme_name\"].yazi.theme" "$THEME_JSON")

  [ -f "$YAZI_CONFIG_FILE" ] || return # Don't error if file doesn't exist

  if grep -q "^theme = " "$YAZI_CONFIG_FILE"; then
    sed -i.bak -E "s|^theme = \".*\"|theme = \"$yazi_theme\"|" "$YAZI_CONFIG_FILE"
  else
    echo "theme = \"$yazi_theme\"" >> "$YAZI_CONFIG_FILE"
  fi
  rm -f "${YAZI_CONFIG_FILE}.bak"
  printf "yazi… "
}

apply_nushell_theme() {
  local theme_name="$1"
  if ! jq -e ".themes[\"$theme_name\"].nushell" "$THEME_JSON" >/dev/null; then return; fi
  
  mkdir -p "$(dirname "$NUSHELL_THEME_FILE")"
  {
    echo "# Generated by colorselector.sh. Do not edit."
    echo "\$env.config.color_config = {"
    jq -r ".themes[\"$theme_name\"].nushell | to_entries | .[] | \"    \\(.key): \\\"\\(.value|tostring)\\\"\"" "$THEME_JSON"
    echo "}"
  } > "$NUSHELL_THEME_FILE"
  
  printf "nushell… "
}

apply_neovim_theme() {
  local theme_name="$1"
  mkdir -p "$(dirname "$ACTIVE_THEME_FILE")"
  printf '{ "active": "%s" }\n' "$theme_name" > "$ACTIVE_THEME_FILE"
  
  # Attempt to reload via socket
  if [ -n "${NVIM-}" ] && [ -S "$NVIM" ]; then
    nvim --server "$NVIM" --remote-send '<C-\><C-N>:lua require("core.theme").setup()<CR>' &>/dev/null
  elif [ -S "/tmp/nvim.sock" ]; then
    nvim --server "/tmp/nvim.sock" --remote-send '<C-\><C-N>:lua require("core.theme").setup()<CR>' &>/dev/null
  fi
  printf "NeoVim… "
}

# --- Main Execution ---
main() {
  if ! command -v jq >/dev/null 2>&1; then error "jq is required. Please install it."; fi
  if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: $(basename "$0") <theme_slug> | --list"
    exit 0
  fi
  if [[ "$1" == "--list" || "$1" == "-l" ]]; then
    list_themes
    exit 0
  fi

  local selected_theme="$1"
  theme_exists "$selected_theme"

  printf "Applying %s to " "$selected_theme"
  
  render_ghostty_theme "$selected_theme"
  apply_yazi_theme "$selected_theme"
  apply_neovim_theme "$selected_theme"
  apply_nushell_theme "$selected_theme"
  
  # Final success message on a new line
  echo # Newline
  echo "✓ $selected_theme applied. Restart Ghostty if colors did not update automatically."
}

main "$@"
