#!/usr/bin/env bash
# JankyBorders — reload: brew services restart borders
# Docs: https://github.com/FelixKratz/JankyBorders
# Auto-generated by `theme`. Do not edit by hand.

options=(
  style=round                # round | square
  width=5.0
  hidpi=on
  active_color=0xff{{ accent_strip }}
  inactive_color=0xff{{ muted_strip }}
  background_color=0x00000000
  # Ignore invisible system alert windows (ghost borders on empty workspaces)
  blacklist="UserNotificationCenter"
)

borders "${options[@]}"
