oauth_token = "NHl0FhJcdPTztJLAMqWIJWDhFNjw6qYgmfnfepVMA5s.3SEPemX8HNYQyq-4FOYVow26GyWnfEFeUgUVoN-Llfk"
expiration_time = "2025-11-03T11:38:27.353Z"
refresh_token = "hBqW5P-ZGR0pj7I2txkxN6wr2KQqhwAFfnfvMzda29Q.diNBOn07Ivsm7EcKkqX7fhmcj6pTMQDtMYIt_V2DFP8"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "ai:write",
  "queues:write",
  "pipelines:write",
  "secrets_store:write",
  "containers:write",
  "cloudchamber:write",
  "connectivity:admin",
  "offline_access"
]
