# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#101315"

# Main text color
theme[main_fg]="#cacccc"

# Title color for boxes
theme[title]="#cacccc"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#798186"

# Background color of selected item in processes box
theme[selected_bg]="#343d41"

# Foreground color of selected item in processes box
theme[selected_fg]="#798186"

# Color of inactive/disabled text
theme[inactive_fg]="#4b4e55"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#cbc2be"

# Background color of the percentage meters
theme[meter_bg]="#343d41"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#cbc2be"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#aeaeae"
theme[mem_box]="#9fa5a9"
theme[net_box]="#565d60"
theme[proc_box]="#798186"

# Box divider line and small boxes line color
theme[div_line]="#4b4e55"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#9fa5a9"
theme[temp_mid]="#d9dbdc"
theme[temp_end]="#565d60"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#707070"
theme[cpu_mid]="#798186"
theme[cpu_end]="#aeaeae"

# Mem/Disk free meter
theme[free_start]="#aeaeae"
theme[free_mid]="#798186"
theme[free_end]="#707070"

# Mem/Disk cached meter
theme[cached_start]="#798186"
theme[cached_mid]="#707070"
theme[cached_end]="#aeaeae"

# Mem/Disk available meter
theme[available_start]="#d9dbdc"
theme[available_mid]="#565d60"
theme[available_end]="#565d60"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#9fa5a9"
theme[used_mid]="#707070"
theme[used_end]="#798186"

# Download graph colors
theme[download_start]="#d9dbdc"
theme[download_mid]="#565d60"
theme[download_end]="#565d60"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#9fa5a9"
theme[upload_mid]="#707070"
theme[upload_end]="#798186"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#707070"
theme[process_mid]="#798186"
theme[process_end]="#aeaeae"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#101315"
theme[gradient_color_1]="#101315"
theme[gradient_color_2]="#343d41"
theme[gradient_color_3]="#4b4e55"
theme[gradient_color_4]="#4b4e55"
theme[gradient_color_5]="#cacccc"
theme[gradient_color_6]="#cbc2be"
theme[gradient_color_7]="#a5aeb4"
