# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#16242d"

# Main text color
theme[main_fg]="#d6e2ee"

# Title color for boxes
theme[title]="#d6e2ee"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8bc9eb"

# Background color of selected item in processes box
theme[selected_bg]="#243d56"

# Foreground color of selected item in processes box
theme[selected_fg]="#8bc9eb"

# Color of inactive/disabled text
theme[inactive_fg]="#304860"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d6e2ee"

# Background color of the percentage meters
theme[meter_bg]="#243d56"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d6e2ee"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#8bc9eb"
theme[mem_box]="#5e95bc"
theme[net_box]="#4d86b0"
theme[proc_box]="#8bc9eb"

# Box divider line and small boxes line color
theme[div_line]="#304860"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#5e95bc"
theme[temp_mid]="#6fa4c9"
theme[temp_end]="#4d86b0"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#b4e4f6"
theme[cpu_mid]="#6fb8e3"
theme[cpu_end]="#8bc9eb"

# Mem/Disk free meter
theme[free_start]="#8bc9eb"
theme[free_mid]="#6fb8e3"
theme[free_end]="#b4e4f6"

# Mem/Disk cached meter
theme[cached_start]="#6fb8e3"
theme[cached_mid]="#b4e4f6"
theme[cached_end]="#8bc9eb"

# Mem/Disk available meter
theme[available_start]="#6fa4c9"
theme[available_mid]="#4d86b0"
theme[available_end]="#4d86b0"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#5e95bc"
theme[used_mid]="#b4e4f6"
theme[used_end]="#6fb8e3"

# Download graph colors
theme[download_start]="#6fa4c9"
theme[download_mid]="#4d86b0"
theme[download_end]="#4d86b0"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#5e95bc"
theme[upload_mid]="#b4e4f6"
theme[upload_end]="#6fb8e3"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#b4e4f6"
theme[process_mid]="#6fb8e3"
theme[process_end]="#8bc9eb"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#16242d"
theme[gradient_color_1]="#1b2d40"
theme[gradient_color_2]="#243d56"
theme[gradient_color_3]="#304860"
theme[gradient_color_4]="#4d86b0"
theme[gradient_color_5]="#d6e2ee"
theme[gradient_color_6]="#d6e2ee"
theme[gradient_color_7]="#f2fcff"
