# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#05182e"

# Main text color
theme[main_fg]="#f6dcac"

# Title color for boxes
theme[title]="#f6dcac"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#faa968"

# Background color of selected item in processes box
theme[selected_bg]="#134e5a"

# Foreground color of selected item in processes box
theme[selected_fg]="#faa968"

# Color of inactive/disabled text
theme[inactive_fg]="#2a6b78"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#a7c9c6"

# Background color of the percentage meters
theme[meter_bg]="#134e5a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a7c9c6"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#3f8f8a"
theme[mem_box]="#028391"
theme[net_box]="#f85525"
theme[proc_box]="#faa968"

# Box divider line and small boxes line color
theme[div_line]="#2a6b78"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#028391"
theme[temp_mid]="#e97b3c"
theme[temp_end]="#f85525"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#8cbfb8"
theme[cpu_mid]="#3f8f8a"
theme[cpu_end]="#3f8f8a"

# Mem/Disk free meter
theme[free_start]="#3f8f8a"
theme[free_mid]="#3f8f8a"
theme[free_end]="#8cbfb8"

# Mem/Disk cached meter
theme[cached_start]="#3f8f8a"
theme[cached_mid]="#8cbfb8"
theme[cached_end]="#3f8f8a"

# Mem/Disk available meter
theme[available_start]="#e97b3c"
theme[available_mid]="#f85525"
theme[available_end]="#f85525"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#028391"
theme[used_mid]="#8cbfb8"
theme[used_end]="#3f8f8a"

# Download graph colors
theme[download_start]="#e97b3c"
theme[download_mid]="#f85525"
theme[download_end]="#f85525"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#028391"
theme[upload_mid]="#8cbfb8"
theme[upload_end]="#3f8f8a"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#8cbfb8"
theme[process_mid]="#3f8f8a"
theme[process_end]="#3f8f8a"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#05182e"
theme[gradient_color_1]="#0a2540"
theme[gradient_color_2]="#134e5a"
theme[gradient_color_3]="#2a6b78"
theme[gradient_color_4]="#3f8f8a"
theme[gradient_color_5]="#f6dcac"
theme[gradient_color_6]="#a7c9c6"
theme[gradient_color_7]="#f6dcac"
