# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0c0b0c"

# Main text color
theme[main_fg]="#FAFCFB"

# Title color for boxes
theme[title]="#FAFCFB"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b59790"

# Background color of selected item in processes box
theme[selected_bg]="#584e51"

# Foreground color of selected item in processes box
theme[selected_fg]="#b59790"

# Color of inactive/disabled text
theme[inactive_fg]="#584e51"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#cfd3cd"

# Background color of the percentage meters
theme[meter_bg]="#584e51"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#cfd3cd"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#c4d8e2"
theme[mem_box]="#87a9b0"
theme[net_box]="#c38b7b"
theme[proc_box]="#b59790"

# Box divider line and small boxes line color
theme[div_line]="#584e51"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#87a9b0"
theme[temp_mid]="#6B5E73"
theme[temp_end]="#c38b7b"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#a5a0b6"
theme[cpu_mid]="#b59790"
theme[cpu_end]="#c4d8e2"

# Mem/Disk free meter
theme[free_start]="#c4d8e2"
theme[free_mid]="#b59790"
theme[free_end]="#a5a0b6"

# Mem/Disk cached meter
theme[cached_start]="#b59790"
theme[cached_mid]="#a5a0b6"
theme[cached_end]="#c4d8e2"

# Mem/Disk available meter
theme[available_start]="#6B5E73"
theme[available_mid]="#c38b7b"
theme[available_end]="#c38b7b"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#87a9b0"
theme[used_mid]="#a5a0b6"
theme[used_end]="#b59790"

# Download graph colors
theme[download_start]="#6B5E73"
theme[download_mid]="#c38b7b"
theme[download_end]="#c38b7b"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#87a9b0"
theme[upload_mid]="#a5a0b6"
theme[upload_end]="#b59790"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#a5a0b6"
theme[process_mid]="#b59790"
theme[process_end]="#c4d8e2"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#0c0b0c"
theme[gradient_color_1]="#0c0b0c"
theme[gradient_color_2]="#584e51"
theme[gradient_color_3]="#584e51"
theme[gradient_color_4]="#584e51"
theme[gradient_color_5]="#FAFCFB"
theme[gradient_color_6]="#cfd3cd"
theme[gradient_color_7]="#e2dddc"
