# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0C1014"

# Main text color
theme[main_fg]="#D6E9E6"

# Title color for boxes
theme[title]="#D6E9E6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#4D7180"

# Background color of selected item in processes box
theme[selected_bg]="#355864"

# Foreground color of selected item in processes box
theme[selected_fg]="#4D7180"

# Color of inactive/disabled text
theme[inactive_fg]="#355864"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#D6E9E6"

# Background color of the percentage meters
theme[meter_bg]="#355864"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#D6E9E6"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#8D90AA"
theme[mem_box]="#4E9B86"
theme[net_box]="#B65D52"
theme[proc_box]="#4D7180"

# Box divider line and small boxes line color
theme[div_line]="#355864"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#4E9B86"
theme[temp_mid]="#C39C5D"
theme[temp_end]="#B65D52"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#5E9BAF"
theme[cpu_mid]="#4D7180"
theme[cpu_end]="#8D90AA"

# Mem/Disk free meter
theme[free_start]="#8D90AA"
theme[free_mid]="#4D7180"
theme[free_end]="#5E9BAF"

# Mem/Disk cached meter
theme[cached_start]="#4D7180"
theme[cached_mid]="#5E9BAF"
theme[cached_end]="#8D90AA"

# Mem/Disk available meter
theme[available_start]="#C39C5D"
theme[available_mid]="#B65D52"
theme[available_end]="#B65D52"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#4E9B86"
theme[used_mid]="#5E9BAF"
theme[used_end]="#4D7180"

# Download graph colors
theme[download_start]="#C39C5D"
theme[download_mid]="#B65D52"
theme[download_end]="#B65D52"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#4E9B86"
theme[upload_mid]="#5E9BAF"
theme[upload_end]="#4D7180"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#5E9BAF"
theme[process_mid]="#4D7180"
theme[process_end]="#8D90AA"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#0C1014"
theme[gradient_color_1]="#355864"
theme[gradient_color_2]="#355864"
theme[gradient_color_3]="#355864"
theme[gradient_color_4]="#355864"
theme[gradient_color_5]="#D6E9E6"
theme[gradient_color_6]="#D6E9E6"
theme[gradient_color_7]="#F1FCFA"
