-- ~/.config/nvim/lua/themes/material.lua
-- Comprehensive local palette for Material (Deep Ocean)

local M = {}

function M.build(P)
  local B = P.base

  local diag = {
    Error = { fg = "$red", bold = true },
    Warn  = { fg = "$yellow", bold = true },
    Info  = { fg = "$blue" },
    Hint  = { fg = "$cyan" },
  }

  return {
    base_palette = {
      Normal        = { fg = "$fg", bg = "$bg0" },
      NormalNC      = { fg = "$fg", bg = "$bg0" },
      NormalFloat   = { fg = "$fg", bg = "$bg1" },
      FloatBorder   = { fg = "$bg3", bg = "$bg0" },
      WinSeparator  = { fg = "$bg2", bg = "$bg0" },
      SignColumn    = { bg = "$bg0" },
      VertSplit     = { fg = "$bg2", bg = "$bg0" },
      StatusLine    = { fg = "$fg", bg = "$bg1" },
      StatusLineNC  = { fg = "$gray", bg = "$bg0" },
      CursorLine    = { bg = "$bg1" },
      CursorColumn  = { bg = "$bg1" },
      ColorColumn   = { bg = "$bg1" },
      LineNr        = { fg = "$gray" },
      CursorLineNr  = { fg = "$blue", bold = true },
      Visual        = { bg = "$bg3" },
      Search        = { fg = "$bg0", bg = "$yellow" },
      IncSearch     = { fg = "$bg0", bg = "$magenta", italic = true },
      Pmenu         = { fg = "$fg", bg = "$bg2" },
      PmenuSel      = { fg = "$bg0", bg = "$blue", bold = true },
      PmenuSbar     = { bg = "$bg2" },
      PmenuThumb    = { bg = "$bg3" },
      TabLine       = { fg = "$gray", bg = "$bg1" },
      TabLineSel    = { fg = "$fg", bg = "$bg3", bold = true },
      TabLineFill   = { fg = "$bg2", bg = "$bg0" },
      MatchParen    = { fg = "$magenta", bold = true },
      Title         = { fg = "$magenta", bold = true },
      Folded        = { fg = "$gray", bg = "$bg1", italic = true },
      FoldColumn    = { fg = "$gray", bg = "$bg0" },
      NonText       = { fg = "$bg3" },
      Whitespace    = { fg = "$bg3" },
      SpecialKey    = { fg = "$cyan" },
      Directory     = { fg = "$blue", bold = true },

      DiffAdd       = { bg = "$green", fg = "$bg0" },
      DiffChange    = { bg = "$bg3", fg = "$fg" },
      DiffDelete    = { bg = "$red",   fg = "$bg0" },
      DiffText      = { bg = "$blue",  fg = "$bg0", bold = true },

      Comment       = { fg = "$gray", italic = true },
      Keyword       = { fg = "$magenta", bold = true },
      Statement     = { link = "Keyword" },
      Type          = { fg = "$yellow" },
      Identifier    = { fg = "$fg" },
      Function      = { fg = "$blue", bold = true },
      Constant      = { fg = "$cyan" },
      String        = { fg = "$green" },
      Number        = { fg = "$yellow" },
      Boolean       = { fg = "$yellow", bold = true },
      Operator      = { fg = "$fg" },
      Delimiter     = { fg = "$gray" },
      PreProc       = { fg = "$magenta" },
      Special       = { fg = "$cyan" },

      -- Mini.statusline/tabline groups
      MiniStatuslineModeNormal   = { fg = "$bg0", bg = "$blue",    bold = true },
      MiniStatuslineModeInsert   = { fg = "$bg0", bg = "$green",   bold = true },
      MiniStatuslineModeVisual   = { fg = "$bg0", bg = "$magenta", bold = true },
      MiniStatuslineModeReplace  = { fg = "$bg0", bg = "$yellow",  bold = true },
      MiniStatuslineModeCommand  = { fg = "$bg0", bg = "$cyan",    bold = true },
      MiniStatuslineModeOther    = { fg = "$bg0", bg = "$gray",    bold = true },
      MiniStatuslineDevinfo      = { fg = "$fg",  bg = "$bg1" },
      MiniStatuslineFilename     = { fg = "$fg",  bg = "$bg0" },
      MiniStatuslineFileinfo     = { fg = "$fg",  bg = "$bg1" },
      MiniStatuslineInactive     = { fg = "$gray",bg = "$bg0" },

      MiniTablineCurrent         = { fg = "$fg",  bg = "$bg2", bold = true },
      MiniTablineVisible         = { fg = "$fg",  bg = "$bg1" },
      MiniTablineHidden          = { fg = "$gray",bg = "$bg0" },
      MiniTablineFill            = { fg = "$bg0", bg = "$bg0" },
      MiniTablineModifiedCurrent = { fg = "$yellow", bg = "$bg2", bold = true },
      MiniTablineModifiedVisible = { fg = "$yellow", bg = "$bg1" },
      MiniTablineModifiedHidden  = { fg = "$yellow", bg = "$bg0" },
    },

    syntax_highlighting = {
      Error      = diag.Error,
      Todo       = { fg = "$bg0", bg = "$yellow", bold = true },
      Underlined = { underline = true },
    },

    ui_elements = {
      WinBar       = { fg = "$fg", bg = "$bg1", bold = true },
      WinBarNC     = { fg = "$gray", bg = "$bg0" },
      QuickFixLine = { bg = "$bg2" },
    },

    diagnostic_colors = {
      DiagnosticError            = diag.Error,
      DiagnosticWarn             = diag.Warn,
      DiagnosticInfo             = diag.Info,
      DiagnosticHint             = diag.Hint,
      DiagnosticSignError        = { fg = "$red",    bg = "$bg0" },
      DiagnosticSignWarn         = { fg = "$yellow", bg = "$bg0" },
      DiagnosticSignInfo         = { fg = "$blue",   bg = "$bg0" },
      DiagnosticSignHint         = { fg = "$cyan",   bg = "$bg0" },
      DiagnosticUnderlineError   = { sp = "$red",    undercurl = true },
      DiagnosticUnderlineWarn    = { sp = "$yellow", undercurl = true },
      DiagnosticUnderlineInfo    = { sp = "$blue",   undercurl = true },
      DiagnosticUnderlineHint    = { sp = "$cyan",   undercurl = true },
      DiagnosticVirtualTextError = { fg = "$red",    bg = "$bg1" },
      DiagnosticVirtualTextWarn  = { fg = "$yellow", bg = "$bg1" },
      DiagnosticVirtualTextInfo  = { fg = "$blue",   bg = "$bg1" },
      DiagnosticVirtualTextHint  = { fg = "$cyan",   bg = "$bg1" },
      LspReferenceText           = { bg = "$bg2" },
      LspReferenceRead           = { bg = "$bg2" },
      LspReferenceWrite          = { bg = "$bg2" },
      LspSignatureActiveParameter= { fg = "$yellow", bold = true },
    },

    plugin_specific = {
      -- fzf-lua
      FzfLuaNormal         = { fg = "$fg",  bg = "$bg2" },
      FzfLuaBorder         = { fg = "$bg3", bg = "$bg0" },
      FzfLuaTitle          = { fg = "$bg0", bg = "$blue", bold = true },
      FzfLuaPreviewNormal  = { fg = "$fg",  bg = "$bg1" },
      FzfLuaPrompt         = { fg = "$fg",  bg = "$bg5", bold = true },

      GitSignsAdd          = { fg = "$green" },
      GitSignsChange       = { fg = "$yellow" },
      GitSignsDelete       = { fg = "$red" },

      NoiceCmdline        = { fg = "$fg", bg = "$bg5", bold = true },
      NoiceCmdlinePopup   = { fg = "$fg", bg = "$bg3" },
      NoiceCmdlineIcon    = { fg = "$blue" },
      NotifyINFOBorder    = { fg = "$blue",   bg = "$bg0" },
      NotifyWARNBorder    = { fg = "$yellow", bg = "$bg0" },
      NotifyERRORBorder   = { fg = "$red",    bg = "$bg0" },
      NotifyDEBUGBorder   = { fg = "$gray",   bg = "$bg0" },
      NotifyTRACEBorder   = { fg = "$magenta",bg = "$bg0" },

      -- hipatterns + render-markdown callouts
      HiPatternTodo       = { fg = "$bg0", bg = "$yellow",  bold = true },
      HiPatternFixme      = { fg = "$bg0", bg = "$red",     bold = true },
      HiPatternHack       = { fg = "$bg0", bg = "$magenta", bold = true },
      HiPatternNote       = { fg = "$bg0", bg = "$blue",    bold = true },

      RenderMarkdownInfo    = { fg = (P.extras.render_markdown and P.extras.render_markdown.color_fg) or "$bg0", bg = (P.extras.render_markdown and P.extras.render_markdown.color1_bg) or "$blue" },
      RenderMarkdownWarn    = { fg = (P.extras.render_markdown and P.extras.render_markdown.color_fg) or "$bg0", bg = (P.extras.render_markdown and P.extras.render_markdown.color3_bg) or "$cyan" },
      RenderMarkdownError   = { fg = (P.extras.render_markdown and P.extras.render_markdown.color_fg) or "$bg0", bg = (P.extras.render_markdown and P.extras.render_markdown.color6_bg) or "$magenta" },
      RenderMarkdownSuccess = { fg = (P.extras.render_markdown and P.extras.render_markdown.color_fg) or "$bg0", bg = (P.extras.render_markdown and P.extras.render_markdown.color2_bg) or "$green" },
      RenderMarkdownHint    = { fg = (P.extras.render_markdown and P.extras.render_markdown.color_fg) or "$bg0", bg = (P.extras.render_markdown and P.extras.render_markdown.color4_bg) or "$blue" },
      RenderMarkdownQuote   = { fg = (P.extras.render_markdown and P.extras.render_markdown.color_fg) or "$bg0", bg = (P.extras.render_markdown and P.extras.render_markdown.color5_bg) or "$green" },
      RenderMarkdownCodeInline = { fg = (P.extras.render_markdown and P.extras.render_markdown.color_fg) or "$bg0", bg = (P.extras.render_markdown and P.extras.render_markdown.colorInline_bg) or "$bg3" },
    },

    treesitter_groups = {
      ["@comment"]            = { link = "Comment" },
      ["@punctuation"]        = { fg = "$gray" },
      ["@operator"]           = { fg = "$fg" },
      ["@keyword"]            = { link = "Keyword" },
      ["@keyword.return"]     = { fg = "$magenta", bold = true },
      ["@type"]               = { link = "Type" },
      ["@type.builtin"]       = { fg = "$yellow", italic = true },
      ["@constant"]           = { link = "Constant" },
      ["@constant.builtin"]   = { fg = "$cyan", bold = true },
      ["@string"]             = { link = "String" },
      ["@number"]             = { link = "Number" },
      ["@boolean"]            = { link = "Boolean" },
      ["@function"]           = { link = "Function" },
      ["@function.builtin"]   = { fg = "$blue", bold = true },
      ["@function.parameter"] = { fg = "$fg", italic = true },
      ["@variable"]           = { fg = "$fg" },
      ["@variable.builtin"]   = { fg = "$cyan", italic = true },
      ["@property"]           = { fg = "$fg" },
      ["@field"]              = { fg = "$fg" },
      ["@namespace"]          = { fg = "$magenta", bold = true },
      ["@module"]             = { fg = "$magenta" },
      ["@punctuation.bracket"]= { fg = "$gray" },
      ["@punctuation.delimiter"] = { fg = "$gray" },
    },

    lsp_semantic_tokens = {
      ["@lsp.type.namespace"] = { fg = "$magenta", bold = true },
      ["@lsp.type.class"]     = { fg = "$yellow",  bold = true },
      ["@lsp.type.enum"]      = { fg = "$yellow" },
      ["@lsp.type.interface"] = { fg = "$yellow", italic = true },
      ["@lsp.type.struct"]    = { fg = "$yellow" },
      ["@lsp.type.type"]      = { link = "@type" },
      ["@lsp.type.parameter"] = { fg = "$fg", italic = true },
      ["@lsp.type.variable"]  = { fg = "$fg" },
      ["@lsp.type.property"]  = { fg = "$fg" },
      ["@lsp.type.enumMember"]= { fg = "$cyan" },
      ["@lsp.type.event"]     = { fg = "$magenta" },
      ["@lsp.type.function"]  = { link = "@function" },
      ["@lsp.type.method"]    = { link = "@function" },
      ["@lsp.type.macro"]     = { fg = "$magenta", bold = true },

      ["@lsp.mod.readonly"]   = { italic = true },
      ["@lsp.mod.static"]     = { underline = true },
      ["@lsp.mod.deprecated"] = { strikethrough = true },
      ["@lsp.mod.defaultLibrary"] = { fg = "$gray", italic = true },
    },

    markdown_groups = {
      markdownH1 = { fg = "$blue",   bold = true },
      markdownH2 = { fg = "$magenta",bold = true },
      markdownH3 = { fg = "$cyan",   bold = true },
      markdownCode = { fg = "$green" },
      markdownBlockquote = { fg = "$gray", italic = true },
      markdownTableDelimiter = { fg = "$gray" },
    },
  }
end

return M
