-- Omarchy themes — generated by `theme joker-vibe`. Do not edit by hand.
-- All theme plugins eager-loaded so switching never waits for Lazy install.
return {
  {
      "catppuccin/nvim", lazy = false,
      name = "catppuccin",
      priority = 1000,
    },
  {
  		"catppuccin/nvim", lazy = false,
  		name = "catppuccin",
  		priority = 1000,
  		opts = {
  			flavour = "latte",
  		},
  	},
  { "neanias/everforest-nvim", lazy = false },
  {
      "kepano/flexoki-neovim", lazy = false,
      priority = 1000,
    },
  { "ellisonleao/gruvbox.nvim", lazy = false },
  {
      "bjarneo/aether.nvim", lazy = false,
      branch = "v3",
      name = "aether",
      priority = 1000,
      opts = {
        colors = {
          bg = "#0C1014",
          dark_bg = "#070A0D",
          darker_bg = "#040608",
          lighter_bg = "#2B4D48",
  
          fg = "#ECFFFE",
          dark_fg = "#2B4D48",
          light_fg = "#ECFFFE",
          bright_fg = "#FFFFFF",
          muted = "#2B4D48",
  
          red = "#FF5A5F",
          yellow = "#FFC14D",
          orange = "#FFD177",
          green = "#00D46A",
          cyan = "#00F0FF",
          blue = "#4DB8FF",
          magenta = "#C07BFF",
          brown = "#2B4D48",
  
          bright_red = "#FF7B7F",
          bright_yellow = "#FFD177",
          bright_green = "#32F08A",
          bright_cyan = "#68FFFF",
          bright_blue = "#7CCFFF",
          bright_magenta = "#D39BFF",
  
          accent = "#4DB8FF",
          cursor = "#FFFFFF",
          foreground = "#ECFFFE",
          background = "#0C1014",
          selection = "#2B4D48",
          selection_foreground = "#FFFFFF",
          selection_background = "#2B4D48",
        },
      },
    },
  { "rebelot/kanagawa.nvim", lazy = false },
  {
      "omacom-io/lumon.nvim", lazy = false,
      priority = 1000,
    },
  { "tahayvr/matteblack.nvim", lazy = false, lazy = false, priority = 1000 },
  { "EdenEast/nightfox.nvim", lazy = false },
  {
      "ribru17/bamboo.nvim", lazy = false,
      priority = 1000,
    },
  {
      "OldJobobo/retro-82.nvim", lazy = false,
      priority = 1000,
    },
  { "rose-pine/neovim", lazy = false, name = "rose-pine" },
  { "ficcdaf/ashen.nvim", lazy = false },
  {
  		"folke/tokyonight.nvim", lazy = false,
  		priority = 1000,
  	},
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = function()
        local w = "aether"
        if not pcall(vim.cmd.colorscheme, w) then
          local a = (w:gsub("%-%a+$", ""))
          if a == w or not pcall(vim.cmd.colorscheme, a) then
            pcall(vim.cmd.colorscheme, "tokyonight")
          end
        end
      end,
    },
  },
}
