# ~/.config/zsh/zshrc
# Main Zsh configuration file

# Source all module files
for module in "$HOME/.config/zsh/modules"/*.zsh; do
  source "$module" >/dev/null 2>&1 || echo "Failed to source $module"
done

# History settings
HISTSIZE=5000                  # Max history entries in memory
HISTFILE="$HOME/.zsh_history"  # History file location
SAVEHIST=$HISTSIZE             # Max history entries to save
HISTDUP=erase                  # Remove duplicates from history
HISTORY_IGNORE="mv*|ls*|lt*|ld*|tree*|bi*|or*|cs*|\$*|or|cp*|..*|mtt|source*|bu|brm*|la*"  # Ignore these patterns

# Shell options
setopt auto_cd               # Cd into directories without typing `cd`
setopt appendhistory         # Append to history file
setopt sharehistory          # Share history across sessions
setopt hist_ignore_space     # Ignore commands starting with space
setopt hist_ignore_all_dups  # Remove all duplicates
setopt hist_save_no_dups     # Don’t save duplicates to file
setopt hist_ignore_dups      # Ignore consecutive duplicates
setopt hist_find_no_dups     # Don’t show duplicates in search

# Keybindings (vi mode)
bindkey -v
bindkey '^[[A' history-search-backward  # Up arrow
bindkey '^[[B' history-search-forward   # Down arrow
bindkey '^[w' kill-region               # Alt+w

# export TERM=xterm command ssh "$@"


[ -s "/Users/schingon/.bun/_bun" ] && source "/Users/schingon/.bun/_bun"


# FZF keybindings and completions This needs to be sourced before compinit
if [[ -f "$(brew --prefix)/opt/fzf/shell/key-bindings.zsh" ]]; then
  source "$(brew --prefix)/opt/fzf/shell/key-bindings.zsh"

  # -- Remap ALT-C to CTRL-L for fzf directory change -- This overwrites the default 'clear-screen' binding for CTRL-L.
  bindkey '^L' fzf-cd-widget
fi
# FZF keybindings and completions This needs to be sourced before compinit

autoload -Uz compinit && compinit

# Case-insensitive matching
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

# Fallback to plain file completion
zstyle ':completion:*' completer _complete _files

bindkey '^I' expand-or-complete
